services:
  # dev:
  #   build: .
  #   env_file: .env/.env.test
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - .:/app
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   depends_on:
  #     - postgres
  #     - minio
  #   working_dir: /app
  minio:
    volumes:
       - minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    image: minio/minio:RELEASE.2023-12-02T10-51-33Z-cpuv1
    environment:
    - MINIO_ROOT_USER=docker
    - MINIO_ROOT_PASSWORD=dockerdocker
    command: server /data --console-address ":9001"
  postgres:
    image: postgres:14.5
    ports:
      - "5432:5432"
    volumes:
       - ./src/lib/lib/model/initdb.sql:/docker-entrypoint-initdb.d/schema.sql
       - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=intelfeed-devdb-secret
      - POSTGRES_DB=intelfeed
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped

  # jaeger:
  #   profiles:
  #     - services
  #     - test
  #   image: jaegertracing/all-in-one:${JAEGER_VERSION:-latest}
  #   ports:
  #     - "16686:16686"
  #     - "4318:4318"
  #   environment:
  #     - LOG_LEVEL=debug

  # beanstalk:
  #   image: schickling/beanstalkd
  #   ports:
  #     - "11300:11300"
  # beanstalk-console:
  #   image: schickling/beanstalkd-console
  #   ports: 
  #     - "2080:2080"
  # redis:
  #   image: redis:7.0.3
  #   ports:
  #     - "6379:6379"
  # redis-insight:
  #   image: redislabs/redisinsight:1.6.3
  #   restart: always
  #   ports:
  #     - "5540:5540"
  #   volumes:
  #     - redis-insight:/data
volumes:
    minio:
    postgres:
    pgadmin: